export const defaultThemeVariables = {
  color: {
    orange: '#FF8440',
    orangeDark: '#E86825',
    orangePale: '#FFE1BE',
    black: '#000',
    blackLighter: '#1C1C23',
    white: '#fff',
    grey: '#9F9C99',
    greyDark: '#7f7b77',
    greyLight: '#EEE',
    greyLightSecondary: '#C4C4C4',
    greyLighter: '#BFBDBC',
    beigePale: '#F9F7F3',
    beigePaleLight: '#F3EFE8',
    beigePaleDark: '#D6D2CE',
    greyBlueLight: '#f8f9fa',
    green: '#008556',
    greenPale: '#D6F3E2',
    red: '#de1c22',
  },
  fontSizeGlobal: {
    regular: '16px',
    xxl: '15px',
    xl: '14px',
  },
  fontSize: {
    bigTitle: '32px',
    regularTitle: '24px',
    bigger: '22px',
    big: '20px',
    regularBig: '18px',
    regular: '16px',
    middle: '14px',
    small: '12px',
  },
  margins: {
    small: '10px',
    base: '20px',
    big: '40px',
  },
  fontFamily: {
    montserrat: 'Montserrat, sans-serif',
  },
  fontWeight: {
    regular: 400,
    medium: 500,
    bold: 700,
  },
  borderRadius: {
    regular: '0px',
    big: '50px',
    small: '8px',
    smaller: '4px',
  },
  transition: {
    regular: '.2s',
  },
  zIndex: {
    zIndexLowest: '-30',
    zIndexLower: '-20',
    zIndexLow: '-10',
    zIndexDefault: 'auto',
    zIndexHigh: '10',
    zIndexHigher: '20',
    zIndexHighest: '30',
  },
  padding: {
    container: {
      base: '50px',
      small: '30px',
      mobile: '20px',
      min: '8px',
    },
    innerOffset: {
      base: '20px',
      small: '8px',
    },
  },
}
